/**
 * T5 — Expert (v0.1) — PRESERVED for benchmarking only.
 *
 * 3-ply minimax with the same eval as T4. Deterministic (no temperature in
 * move selection) — true argmax. Same offer/ability logic as T4 for now.
 *
 * This file is the frozen v0.1 implementation. v0.2 lives in `t5.ts`.
 * Both export a `Bot` with `id: 'T5'`; the benchmark imports them under
 * different local names. Do not edit this file.
 *
 * Performance note: 3-ply is significantly slower than 2-ply. We cap the
 * candidate branching by sorting candidates by 1-ply eval and only deep-
 * searching the top-K. K=6 is a reasonable trade between strength and speed.
 *
 * Iteration: ability candidates always survive the top-K cutoff and get a
 * +1 depth extension, so plans like "freeze → walk → walk" become visible
 * at nominal depth 3. Without this, ability candidates that score poorly
 * at depth 1 get pruned and the bot never sees their downstream payoff —
 * which is what kept the ablation flatlining even after board-aware eval.
 */

import type { BoardState } from '../../../lib/run/types';
import { applyBotAction } from './apply';
import {
  evalState,
  legalCandidates,
  rookieCanBeCapturedThisTurn,
  valueOfOffer,
} from './shared';
import { settleEnemyTurns } from './t3';
import type { Bot, BotAction, BotContext } from '../types';

const DEEP_BRANCH_K = 6;
const ABILITY_DEPTH_BONUS = 1;

export const T5_V01: Bot = {
  id: 'T5',
  decide(state, ctx) {
    if (state.pendingOffer) return pickOfferExpert(state, ctx);

    if (rookieCanBeCapturedThisTurn(state) && hasUsableAegis(state, ctx)) {
      return { kind: 'activate-ability', abilityId: 'aegis' };
    }

    const candidates = legalCandidates(state, ctx.excludedAbilities);
    if (candidates.length === 0) {
      return { kind: 'move', target: { ...state.rookie } };
    }

    // Shallow score for ranking.
    const shallow = candidates.map((c, i) => ({
      i,
      score: searchDepth(state, c, 1),
    }));
    shallow.sort((a, b) => b.score - a.score);

    // Build the deep-search set: top-K regular candidates, but ALL ability
    // candidates always make the cut. A freeze on the wrong target may
    // score poorly at 1-ply (charge consumed for no visible gain) yet pay
    // off across 3-4 plies once the board reorganizes — without inclusion
    // we'd prune those plans before they were tested.
    const deepIdxs = new Set<number>();
    for (const { i } of shallow.slice(0, Math.min(DEEP_BRANCH_K, shallow.length))) {
      deepIdxs.add(i);
    }
    for (let i = 0; i < candidates.length; i++) {
      if (candidates[i].kind !== 'move') deepIdxs.add(i);
    }

    let bestIdx = shallow[0].i;
    let bestScore = -Infinity;
    for (const i of deepIdxs) {
      const isAbility = candidates[i].kind !== 'move';
      const depth = 3 + (isAbility ? ABILITY_DEPTH_BONUS : 0);
      const s = searchDepth(state, candidates[i], depth);
      if (s > bestScore) {
        bestScore = s;
        bestIdx = i;
      }
    }

    const chosen = candidates[bestIdx];
    if (chosen.kind === 'move') return { kind: 'move', target: chosen.target! };
    if (chosen.kind === 'activate-ability')
      return { kind: 'activate-ability', abilityId: chosen.abilityId! };
    return { kind: 'ability-target', abilityId: chosen.abilityId!, target: chosen.target! };
  },
};

function searchDepth(
  state: BoardState,
  candidate: ReturnType<typeof legalCandidates>[number],
  depth: number,
): number {
  const action: BotAction =
    candidate.kind === 'move'
      ? { kind: 'move', target: candidate.target! }
      : candidate.kind === 'activate-ability'
        ? { kind: 'activate-ability', abilityId: candidate.abilityId! }
        : {
            kind: 'ability-target',
            abilityId: candidate.abilityId!,
            target: candidate.target!,
          };
  const after = applyBotAction(state, action);
  if (after === state) return -10_000;
  const settled = settleEnemyTurns(after);
  if (depth <= 1 || settled.status !== 'playing') return evalState(settled);
  const nextCands = legalCandidates(settled, new Set());
  if (nextCands.length === 0) return evalState(settled);
  let best = -Infinity;
  for (const nc of nextCands) {
    const s = searchDepth(settled, nc, depth - 1);
    if (s > best) best = s;
  }
  return best;
}

function hasUsableAegis(state: BoardState, ctx: BotContext): boolean {
  if (ctx.excludedAbilities.has('aegis')) return false;
  const owned = state.abilities.find((a) => a.id === 'aegis');
  if (!owned) return false;
  if (state.shieldUp) return false;
  if (owned.tier !== 5 && owned.usesLeftThisLevel === 0) return false;
  return true;
}

function pickOfferExpert(state: BoardState, ctx: BotContext): BotAction {
  const offer = state.pendingOffer!;
  let bestIdx = -1;
  let bestScore = -Infinity;
  offer.forEach((opt, i) => {
    if (ctx.excludedAbilities.has(opt.id)) return;
    const v = valueOfOffer(state, opt.id, opt.tier, opt.kind);
    if (v > bestScore) {
      bestScore = v;
      bestIdx = i;
    }
  });
  if (bestIdx === -1) return { kind: 'dismiss-offer' };
  return { kind: 'pick-offer', optionIndex: bestIdx as 0 | 1 };
}
