// GENERATED by scripts/bake-postgame-game.ts — do not hand-edit.
// A real Play Rookie game, graded at Stockfish depth 10 by the same
// functions the app uses (analyzeGameMoves + applyBookMoves).
//
// Session 71f9a33c-8060-444e-92c4-a836d0f38603 · 2026-09-02

import type { MoveStats } from '@/components/shared/ActivityComplete'

export const REAL_GAME = {
  sessionId: "71f9a33c-8060-444e-92c4-a836d0f38603",
  playedOn: "2026-09-02",
  playerColor: "white",
  outcome: "win" as 'win' | 'loss' | 'draw' | 'resign',
  resultMethod: "checkmate",
  rookieDifficulty: 5,
  totalMoves: 95,
  accuracy: 84,
  depth: 10,
  /** The legendary move(s) the engine found, for the page's caption. */
  legendary: [{"moveNumber":37,"san":"Bxe5"},{"moveNumber":79,"san":"Rxg4"}],
  openingMoves: ["e4","c6","d4","d5","Nd2","dxe4","Nxe4","Nf6"],
} as const

export const REAL_GAME_STATS: MoveStats = {
  legendary: 2,
  great: 2,
}
