// GENERATED by scripts/witty/build-martian.ts — do not edit by hand.
// Source: witty_alien's real chess.com games. Edit the spec + regenerate.
import type { OpeningTree } from './ruy-lopez'

export const WITTY_ALIEN_MARTIAN: OpeningTree = {
  "id": "witty-alien-martian",
  "name": "Martian Gambit",
  "slug": "witty-alien-martian",
  "description": "Witty_Alien's two-knight sacrifice against the Caro-Kann ...Bf5: 5.Ng5, 7.Ne6!! and 11.Nxf7!! tear open the king. Unsound by the engine, lethal in bullet. Built from his real games (~85% win rate).",
  "color": "#8B5CF6",
  "colorDark": "#6D28D9",
  "completionOrder": [
    "wam-1",
    "wam-2",
    "wam-3",
    "wam-4",
    "wam-dev-5e6",
    "wam-dev-5h6",
    "wam-dev-8Bf5",
    "wam-test-1"
  ],
  "nodes": [
    {
      "id": "wam-1",
      "name": "The Caro Setup",
      "moves": [
        "e4",
        "1...c6 d4",
        "2...d5 Nd2"
      ],
      "description": "The Martian Gambit — Witty's two-knight sacrifice against the Caro-Kann. It starts as a normal opening; the fireworks come later.",
      "type": "main",
      "row": 0,
      "col": 0,
      "lineFrom": null,
      "unlockedBy": null,
      "side": "white"
    },
    {
      "id": "wam-2",
      "name": "Both Knights Loaded",
      "moves": [
        "3...dxe4 Nxe4",
        "4...Bf5 Ng5",
        "5...Bg6 N1f3"
      ],
      "description": "Black develops the bishop to f5. Instead of retreating, you throw the knight to g5 and bring the second one out — both aimed at f7.",
      "type": "main",
      "row": 1,
      "col": 0,
      "lineFrom": "wam-1",
      "unlockedBy": null,
      "side": "white"
    },
    {
      "id": "wam-3",
      "name": "The First Sacrifice",
      "moves": [
        "6...h6 Ne6",
        "7...fxe6 Ne5",
        "8...Bf7 Bc4"
      ],
      "description": "Black kicks with h6. This is the moment — don't retreat. Sacrifice the knight on e6 and rip the king's cover off.",
      "type": "main",
      "row": 2,
      "col": 0,
      "lineFrom": "wam-2",
      "unlockedBy": null,
      "side": "white"
    },
    {
      "id": "wam-4",
      "name": "The Second Sacrifice",
      "moves": [
        "9...Nf6 Qd3",
        "10...Nbd7 Nxf7",
        "11...Kxf7 Qf5"
      ],
      "description": "The attack is loaded. Bring the queen in, then sacrifice the SECOND knight on f7 to drag the king into a mating net.",
      "type": "main",
      "row": 3,
      "col": 0,
      "lineFrom": "wam-3",
      "unlockedBy": null,
      "side": "white"
    },
    {
      "id": "wam-dev-5e6",
      "name": "If 5...e6",
      "moves": [
        "5...e6 N1f3",
        "6...Nd7 Nh4",
        "7...Bg6 Nxg6"
      ],
      "description": "Instead of Bg6, Black plays e6 to blunt the attack. No sac here — just win the bishop pair cleanly.",
      "type": "deviation",
      "row": 1,
      "col": -1,
      "lineFrom": "wam-2",
      "unlockedBy": null,
      "side": "white"
    },
    {
      "id": "wam-dev-5h6",
      "name": "If 5...h6",
      "moves": [
        "5...h6 Nxf7",
        "6...Kxf7 Nf3",
        "7...Nd7 Nh4"
      ],
      "description": "Black kicks the knight immediately with h6. Same answer as the Alien Gambit — sacrifice on f7!",
      "type": "deviation",
      "row": 2,
      "col": -1,
      "lineFrom": "wam-2",
      "unlockedBy": null,
      "side": "white"
    },
    {
      "id": "wam-dev-8Bf5",
      "name": "If 8...Bf5",
      "moves": [
        "8...Bf5 g4",
        "9...Bh7 Bc4",
        "10...Nd7 Qe2"
      ],
      "description": "After the Ne6 sac and Ne5, Black retreats the bishop to f5 instead of f7. Kick it and keep the attack rolling.",
      "type": "deviation",
      "row": 3,
      "col": -1,
      "lineFrom": "wam-3",
      "unlockedBy": null,
      "side": "white"
    },
    {
      "id": "wam-test-1",
      "name": "Lvl 1 Test",
      "moves": [],
      "description": "Test time. Play the Martian — the double-knight sacrifice main line plus the key deviations. No hints.",
      "type": "test",
      "row": 4,
      "col": 0,
      "lineFrom": "wam-4",
      "unlockedBy": null,
      "side": "white"
    }
  ]
}
