// GENERATED by scripts/witty/build-elephant.ts — do not edit by hand.
// Source: witty_alien's real chess.com games. Edit the spec + regenerate.
import type { OpeningTree } from './ruy-lopez'

export const WITTY_ALIEN_ELEPHANT: OpeningTree = {
  "id": "witty-alien-elephant",
  "name": "Elephant Gambit",
  "slug": "witty-alien-elephant",
  "description": "Witty_Alien's #1 weapon as Black — 1.e4 e5 2.Nf3 d5, the Elephant Gambit. Offer the pawn, kick the knight, then develop like lightning. 5,622 real games, 67% win rate.",
  "color": "#8B5CF6",
  "colorDark": "#6D28D9",
  "completionOrder": [
    "we-1",
    "we-2",
    "we-3",
    "we-dev-Nxe5",
    "we-dev-d4",
    "we-dev-Nc3",
    "we-dev-Nd4",
    "we-dev-Ng1",
    "we-test-1"
  ],
  "nodes": [
    {
      "id": "we-1",
      "name": "The Elephant Gambit",
      "moves": [
        "1.e4 e5",
        "2.Nf3 d5",
        "3.exd5 e4"
      ],
      "description": "Welcome to the Elephant Gambit — Witty_Alien's favorite weapon as Black, in nearly half his games against 1.e4. Offer a pawn, ignore it, kick the knight.",
      "type": "main",
      "row": 0,
      "col": 0,
      "lineFrom": null,
      "unlockedBy": null,
      "side": "black"
    },
    {
      "id": "we-2",
      "name": "Develop and Castle",
      "moves": [
        "4.Qe2 Nf6",
        "5.Nc3 Be7",
        "6.Nxe4 O-O"
      ],
      "description": "4.Qe2 pins your e4 pawn. No problem — you develop fast and let White waste time holding the extra pawn.",
      "type": "main",
      "row": 1,
      "col": 0,
      "lineFrom": "we-1",
      "unlockedBy": null,
      "side": "black"
    },
    {
      "id": "we-3",
      "name": "Bishop Pair and the e-file",
      "moves": [
        "7.Nxf6+ Bxf6",
        "8.d4 Bf5",
        "9.Be3 Re8"
      ],
      "description": "White won the gambit pawn but had to trade on f6 — handing you the bishop pair. Now cash in your lead: bishops out, rook on the e-file.",
      "type": "main",
      "row": 2,
      "col": 0,
      "lineFrom": "we-2",
      "unlockedBy": null,
      "side": "black"
    },
    {
      "id": "we-dev-Nxe5",
      "name": "If 3.Nxe5",
      "moves": [
        "3.Nxe5 Nf6",
        "4.exd5 Qxd5",
        "5.Nf3 Nc6"
      ],
      "description": "The honest test: instead of taking d5, White grabs the e5 pawn with 3.Nxe5. You're genuinely a pawn down — bet everything on fast development.",
      "type": "deviation",
      "row": 0,
      "col": -1,
      "lineFrom": "we-1",
      "unlockedBy": null,
      "side": "black"
    },
    {
      "id": "we-dev-d4",
      "name": "If 3.d4",
      "moves": [
        "3.d4 Nf6",
        "4.Nxe5 Nxe4",
        "5.Bd3 Bd6"
      ],
      "description": "3.d4 grabs the center instead of a pawn. You develop with tempo and snatch the e4 pawn — a Petroff-style gambit.",
      "type": "deviation",
      "row": 1,
      "col": -1,
      "lineFrom": "we-1",
      "unlockedBy": null,
      "side": "black"
    },
    {
      "id": "we-dev-Nc3",
      "name": "If 3.Nc3",
      "moves": [
        "3.Nc3 d4",
        "4.Ne2 f6",
        "5.d3 Be6"
      ],
      "description": "3.Nc3 attacks your d5 pawn. Don't defend it — push past and gain space.",
      "type": "deviation",
      "row": 2,
      "col": -1,
      "lineFrom": "we-1",
      "unlockedBy": null,
      "side": "black"
    },
    {
      "id": "we-dev-Nd4",
      "name": "If 4.Nd4",
      "moves": [
        "4.Nd4 Qxd5",
        "5.Nb3 Qe5",
        "6.Nc3 Nf6"
      ],
      "description": "Instead of 4.Qe2, White retreats the knight to d4 — passive. Take the pawn back immediately, the queen even hits the knight.",
      "type": "deviation",
      "row": 1,
      "col": 1,
      "lineFrom": "we-2",
      "unlockedBy": null,
      "side": "black"
    },
    {
      "id": "we-dev-Ng1",
      "name": "If 4.Ng1",
      "moves": [
        "4.Ng1 Qxd5",
        "5.Nc3 Qe5",
        "6.Qe2 Nf6"
      ],
      "description": "White's knight crawls all the way back to g1 — totally passive. Grab the free pawn and dominate.",
      "type": "deviation",
      "row": 2,
      "col": 1,
      "lineFrom": "we-2",
      "unlockedBy": null,
      "side": "black"
    },
    {
      "id": "we-test-1",
      "name": "Lvl 1 Test",
      "moves": [],
      "description": "Test time. Play the Elephant — the main line plus every deviation White can throw at you. No hints.",
      "type": "test",
      "row": 3,
      "col": 0,
      "lineFrom": "we-3",
      "unlockedBy": null,
      "side": "black"
    }
  ]
}
