// GENERATED by scripts/witty/build-englund.ts — do not edit by hand.
// Source: witty_alien's real chess.com games. Edit the spec + regenerate.
import type { OpeningTree } from './ruy-lopez'

export const WITTY_ALIEN_ENGLUND: OpeningTree = {
  "id": "witty-alien-englund",
  "name": "Englund Gambit",
  "slug": "witty-alien-englund",
  "description": "Witty_Alien's gambit against 1.d4 — 1...e5! and 2...d6, offering pawns to blow the position open and play on development. Honest: roughly equal, but a fighting weapon.",
  "color": "#8B5CF6",
  "colorDark": "#6D28D9",
  "completionOrder": [
    "weng-1",
    "weng-2",
    "weng-3",
    "weng-dev-c4",
    "weng-test-1"
  ],
  "nodes": [
    {
      "id": "weng-1",
      "name": "The 1...e5 Gambit",
      "moves": [
        "1.d4 e5",
        "2.dxe5 d6",
        "3.Nf3 Nc6"
      ],
      "description": "Witty's answer to 1.d4 — strike with e5 and offer a second pawn with d6 to pry the game open.",
      "type": "main",
      "row": 0,
      "col": 0,
      "lineFrom": null,
      "unlockedBy": null,
      "side": "black"
    },
    {
      "id": "weng-2",
      "name": "Open the Center",
      "moves": [
        "4.Bg5 f6",
        "5.exf6 Nxf6",
        "6.Nc3 Be7"
      ],
      "description": "Hit back at the e5 pawn with f6, recapture, and develop the bishop.",
      "type": "main",
      "row": 1,
      "col": 0,
      "lineFrom": "weng-1",
      "unlockedBy": null,
      "side": "black"
    },
    {
      "id": "weng-3",
      "name": "Castle and Press",
      "moves": [
        "7.e3 O-O",
        "8.Bc4+ Kh8",
        "9.O-O Qe8"
      ],
      "description": "Castle, tuck the king, and lift the queen toward the kingside.",
      "type": "main",
      "row": 2,
      "col": 0,
      "lineFrom": "weng-2",
      "unlockedBy": null,
      "side": "black"
    },
    {
      "id": "weng-dev-c4",
      "name": "If 2.c4",
      "moves": [
        "2.c4 exd4",
        "3.Qxd4 Nc6",
        "4.Qd1 Nf6"
      ],
      "description": "Instead of taking on e5, White plays 2.c4. Grab the d4 pawn and develop with tempo against the early queen.",
      "type": "deviation",
      "row": 0,
      "col": -1,
      "lineFrom": "weng-1",
      "unlockedBy": null,
      "side": "black"
    },
    {
      "id": "weng-test-1",
      "name": "Lvl 1 Test",
      "moves": [],
      "description": "Test time. Play Witty's Englund. No hints.",
      "type": "test",
      "row": 3,
      "col": 0,
      "lineFrom": "weng-3",
      "unlockedBy": null,
      "side": "black"
    }
  ]
}
