// GENERATED by scripts/witty/build-bonjour.ts — do not edit by hand.
// Source: witty_alien's real chess.com games. Edit the spec + regenerate.
import type { OpeningTree } from './ruy-lopez'

export const WITTY_ALIEN_BONJOUR: OpeningTree = {
  "id": "witty-alien-bonjour",
  "name": "Bonjour Variation",
  "slug": "witty-alien-bonjour",
  "description": "Witty_Alien's Nxf7 knight sacrifice against the French Defense — 'Bonjour!' as the king gets dragged out. Built from his real games (~76% win rate).",
  "color": "#8B5CF6",
  "colorDark": "#6D28D9",
  "completionOrder": [
    "wab-1",
    "wab-2",
    "wab-3",
    "wab-4",
    "wab-test-1"
  ],
  "nodes": [
    {
      "id": "wab-1",
      "name": "The French Setup",
      "moves": [
        "e4",
        "1...e6 d4",
        "2...d5 Nd2"
      ],
      "description": "The Bonjour Variation — the Alien Gambit's Nxf7 sacrifice, now against the French Defense.",
      "type": "main",
      "row": 0,
      "col": 0,
      "lineFrom": null,
      "unlockedBy": null,
      "side": "white"
    },
    {
      "id": "wab-2",
      "name": "Bonjour! (the f7 sac)",
      "moves": [
        "3...dxe4 Nxe4",
        "4...Nf6 Ng5",
        "5...h6 Nxf7"
      ],
      "description": "Recapture, leap to g5, and when Black plays h6 — sacrifice on f7. Bonjour!",
      "type": "main",
      "row": 1,
      "col": 0,
      "lineFrom": "wab-1",
      "unlockedBy": "wab-1",
      "side": "white"
    },
    {
      "id": "wab-3",
      "name": "Develop the Attack",
      "moves": [
        "6...Kxf7 Nf3",
        "7...Bd6 Bd3",
        "8...Rf8 O-O"
      ],
      "description": "King on f7. Pour pieces in — Nf3, Bd3 at h7, then castle to open the f-file.",
      "type": "main",
      "row": 2,
      "col": 0,
      "lineFrom": "wab-2",
      "unlockedBy": "wab-2",
      "side": "white"
    },
    {
      "id": "wab-4",
      "name": "Crash Through",
      "moves": [
        "9...Kg8 Re1",
        "10...Nc6 c3",
        "11...Re8 Ne5"
      ],
      "description": "Stack the e-file, solidify, and crash in with Ne5.",
      "type": "main",
      "row": 3,
      "col": 0,
      "lineFrom": "wab-3",
      "unlockedBy": "wab-3",
      "side": "white"
    },
    {
      "id": "wab-test-1",
      "name": "Lvl 1 Test",
      "moves": [],
      "description": "Test time. Play the Bonjour — the f7 sac vs the French. No hints.",
      "type": "test",
      "row": 4,
      "col": 0,
      "lineFrom": "wab-4",
      "unlockedBy": "wab-4",
      "side": "white"
    }
  ]
}
