// GENERATED by scripts/witty/build-danish.ts — do not edit by hand.
// Source: witty_alien's real chess.com games. Edit the spec + regenerate.
import type { OpeningTree } from './ruy-lopez'

export const WITTY_ALIEN_DANISH: OpeningTree = {
  "id": "witty-alien-danish",
  "name": "Danish Gambit",
  "slug": "witty-alien-danish",
  "description": "Witty_Alien's two-pawn Danish Gambit: 1.e4 e5 2.d4 exd4 3.c3! Sacrifice two pawns for two raking bishops and a furious initiative. Built from his real games.",
  "color": "#8B5CF6",
  "colorDark": "#6D28D9",
  "completionOrder": [
    "wd-1",
    "wd-2",
    "wd-3",
    "wd-dev-d5",
    "wd-test-1"
  ],
  "nodes": [
    {
      "id": "wd-1",
      "name": "Two Pawns, Two Bishops",
      "moves": [
        "e4",
        "1...e5 d4",
        "2...exd4 c3"
      ],
      "description": "The Danish Gambit — sacrifice not one but TWO pawns to rip open lines for your bishops.",
      "type": "main",
      "row": 0,
      "col": 0,
      "lineFrom": null,
      "unlockedBy": null,
      "side": "white"
    },
    {
      "id": "wd-2",
      "name": "The Raking Bishops",
      "moves": [
        "3...dxc3 Bc4",
        "4...cxb2 Bxb2",
        "5...Bb4+ Nc3"
      ],
      "description": "Develop the bishops onto their killer diagonals — Bc4 at f7, Bxb2 at g7.",
      "type": "main",
      "row": 1,
      "col": 0,
      "lineFrom": "wd-1",
      "unlockedBy": null,
      "side": "white"
    },
    {
      "id": "wd-3",
      "name": "Mobilize",
      "moves": [
        "6...Nf6 Nf3",
        "7...O-O O-O",
        "8...Bxc3 Bxc3"
      ],
      "description": "Finish development and castle — every piece firing at the king for your two pawns.",
      "type": "main",
      "row": 2,
      "col": 0,
      "lineFrom": "wd-2",
      "unlockedBy": null,
      "side": "white"
    },
    {
      "id": "wd-dev-d5",
      "name": "If 3...d5",
      "moves": [
        "3...d5 e5",
        "4...dxc3 Nf3",
        "5...Nc6 Bd3"
      ],
      "description": "Solid players decline the gambit with 3...d5. No problem — push past with e5 and keep a space edge.",
      "type": "deviation",
      "row": 1,
      "col": -1,
      "lineFrom": "wd-1",
      "unlockedBy": null,
      "side": "white"
    },
    {
      "id": "wd-test-1",
      "name": "Lvl 1 Test",
      "moves": [],
      "description": "Test time. Play the Danish two-pawn gambit. No hints.",
      "type": "test",
      "row": 3,
      "col": 0,
      "lineFrom": "wd-3",
      "unlockedBy": null,
      "side": "white"
    }
  ]
}
