// GENERATED by scripts/witty/build-scandi.ts — do not edit by hand.
// Source: witty_alien's real chess.com games. Edit the spec + regenerate.
import type { OpeningTree } from './ruy-lopez'

export const WITTY_ALIEN_SCANDI: OpeningTree = {
  "id": "witty-alien-scandi",
  "name": "Scandinavian Gambit",
  "slug": "witty-alien-scandi",
  "description": "Witty_Alien's wild double-pawn Scandinavian: 1.e4 d5 2.exd5 c6! 3.dxc6 e5! Give up TWO pawns for a colossal lead in development. Built from his real games (~73%).",
  "color": "#8B5CF6",
  "colorDark": "#6D28D9",
  "completionOrder": [
    "wsc-1",
    "wsc-2",
    "wsc-dev-Nc3",
    "wsc-test-1"
  ],
  "nodes": [
    {
      "id": "wsc-1",
      "name": "Two Pawns for a Storm",
      "moves": [
        "1.e4 d5",
        "2.exd5 c6",
        "3.dxc6 e5"
      ],
      "description": "The Scandinavian Gambit — answer 1.e4 with d5, then sacrifice TWO pawns (c6 and the center) for a colossal development lead.",
      "type": "main",
      "row": 0,
      "col": 0,
      "lineFrom": null,
      "unlockedBy": null,
      "side": "black"
    },
    {
      "id": "wsc-2",
      "name": "Pieces Screaming Out",
      "moves": [
        "4.cxb7 Bxb7",
        "5.Nc3 Bc5",
        "6.d3 Nf6"
      ],
      "description": "Recapture on b7 with the bishop and pour every piece toward the king.",
      "type": "main",
      "row": 1,
      "col": 0,
      "lineFrom": "wsc-1",
      "unlockedBy": "wsc-1",
      "side": "black"
    },
    {
      "id": "wsc-dev-Nc3",
      "name": "If 3.Nc3",
      "moves": [
        "3.Nc3 Nf6",
        "4.d4 cxd5",
        "5.Nf3 Nc6"
      ],
      "description": "White declines the second pawn with 3.Nc3, holding d5. No sac here — just develop and win the pawn back.",
      "type": "deviation",
      "row": 0,
      "col": -1,
      "lineFrom": "wsc-1",
      "unlockedBy": "wsc-2",
      "side": "black"
    },
    {
      "id": "wsc-test-1",
      "name": "Lvl 1 Test",
      "moves": [],
      "description": "Test time. Play the Scandinavian double-pawn gambit. No hints.",
      "type": "test",
      "row": 2,
      "col": 0,
      "lineFrom": "wsc-2",
      "unlockedBy": "wsc-dev-Nc3",
      "side": "black"
    }
  ]
}
