// GENERATED by scripts/witty/build-witty-alien.ts — do not edit by hand.
// Source: witty_alien's real chess.com games. Edit the spec + regenerate.
import type { OpeningTree } from './ruy-lopez'

export const WITTY_ALIEN: OpeningTree = {
  "id": "witty-alien",
  "name": "Alien Gambit",
  "slug": "witty-alien",
  "description": "Witty_Alien's signature knight sacrifice against the Caro-Kann: 1.e4 c6 2.d4 d5 3.Nd2 dxe4 4.Nxe4 Nf6 5.Ng5 h6 6.Nxf7!! The king is dragged out and hunted. Unsound by the engine, lethal in bullet. Built from his real games (~80% win rate).",
  "color": "#8B5CF6",
  "colorDark": "#6D28D9",
  "completionOrder": [
    "wa-1",
    "wa-2",
    "wa-3",
    "wa-4",
    "wa-dev-Bf5",
    "wa-dev-e6",
    "wa-test-1"
  ],
  "nodes": [
    {
      "id": "wa-1",
      "name": "The Caro Setup",
      "moves": [
        "e4",
        "1...c6 d4",
        "2...d5 Nd2"
      ],
      "description": "The Alien Gambit — Witty's signature f7 knight sacrifice against the Caro-Kann. First, the normal setup.",
      "type": "main",
      "row": 0,
      "col": 0,
      "lineFrom": null,
      "unlockedBy": null,
      "side": "white"
    },
    {
      "id": "wa-2",
      "name": "The f7 Sacrifice",
      "moves": [
        "3...dxe4 Nxe4",
        "4...Nf6 Ng5",
        "5...h6 Nxf7"
      ],
      "description": "Recapture, jump to g5 aiming at f7, and when Black kicks with h6 — sacrifice the knight on f7.",
      "type": "main",
      "row": 1,
      "col": 0,
      "lineFrom": "wa-1",
      "unlockedBy": null,
      "side": "white"
    },
    {
      "id": "wa-3",
      "name": "The King Hunt",
      "moves": [
        "6...Kxf7 Nf3",
        "7...c5 Ne5+",
        "8...Kg8 Bc4+"
      ],
      "description": "The king is on f7 with no shelter. Develop with checks — Nf3, Ne5+, Bc4+ — and chase it home.",
      "type": "main",
      "row": 2,
      "col": 0,
      "lineFrom": "wa-2",
      "unlockedBy": null,
      "side": "white"
    },
    {
      "id": "wa-4",
      "name": "Cash In the Attack",
      "moves": [
        "9...e6 O-O",
        "10...Nc6 Ng6",
        "11...Qxd4 Qe2"
      ],
      "description": "King boxed in the corner. Castle to swing the rook onto the f-file, fork with Ng6, and pour the queen in.",
      "type": "main",
      "row": 3,
      "col": 0,
      "lineFrom": "wa-3",
      "unlockedBy": null,
      "side": "white"
    },
    {
      "id": "wa-dev-Bf5",
      "name": "If 5...Bf5",
      "moves": [
        "5...Bf5 N1f3",
        "6...Nbd7 Nh4",
        "7...Bg6 Nxg6"
      ],
      "description": "Instead of h6, Black develops the bishop to f5. No sacrifice — just chase the bishop and grab the bishop pair.",
      "type": "deviation",
      "row": 1,
      "col": -1,
      "lineFrom": "wa-2",
      "unlockedBy": null,
      "side": "white"
    },
    {
      "id": "wa-dev-e6",
      "name": "If 5...e6",
      "moves": [
        "5...e6 N1f3",
        "6...Bd6 Bd3",
        "7...O-O Qe2"
      ],
      "description": "Black plays e6 to keep things solid. No sac — develop classically and aim at the kingside.",
      "type": "deviation",
      "row": 2,
      "col": -1,
      "lineFrom": "wa-2",
      "unlockedBy": null,
      "side": "white"
    },
    {
      "id": "wa-test-1",
      "name": "Lvl 1 Test",
      "moves": [],
      "description": "Test time. Play the Alien Gambit — the f7 sacrifice and king hunt, plus the quiet deviations. No hints.",
      "type": "test",
      "row": 4,
      "col": 0,
      "lineFrom": "wa-4",
      "unlockedBy": null,
      "side": "white"
    }
  ]
}
