import type { AchievementDef } from './types';

/**
 * The achievement catalog (Chess Boxing).
 *
 * Copy lives in code, not the DB (same pattern as the quip pool). Every line
 * is Rookie: short, warm, over-invested, never cruel about the player — the
 * roast targets the situation. Voice rules: .claude/rookie-voice-bible.md.
 *
 * IDs are stable forever — they're stored in user_achievements. Add new
 * achievements freely; never rename or reuse an id.
 *
 * Design (2026-08-24 rework): a first-timer must leave their first workout or
 * bout with 3-5 medals, and nearly every session should tick a ladder.
 *   - "first-*" medals are binary and trivially cheap (one punch, one solve).
 *   - Count ladders start LOW (rung I is reachable in one session) and climb
 *     to the old lifetime numbers — the belt-tier mechanism does the rest.
 */
export const ACHIEVEMENT_CATALOG: AchievementDef[] = [
  // ── Bout ──────────────────────────────────────────────────────────────────
  {
    id: 'bout-ring-time',
    category: 'bout',
    name: 'Ring Time',
    description: 'You stepped into the ring with me. Win or lose, that already puts you ahead of everyone who only talks about it.',
    icon: '/achievements/bout-ring-time.webp',
    thresholds: [1, 5, 25, 100, 500],
  },
  {
    id: 'bout-first-round',
    category: 'bout',
    name: 'Heard the Bell',
    description: 'You survived a full round. Your legs are still under you. I checked.',
    icon: '/achievements/bout-first-round.webp',
  },
  {
    id: 'bout-first-blood',
    category: 'bout',
    name: 'First Blood',
    description: "Your first win. I'm framing this. I already framed it.",
    icon: '/achievements/bout-first-blood.webp',
  },
  {
    id: 'bout-learning-tax',
    category: 'bout',
    name: 'Learning Tax',
    description: "Your first loss. Everyone pays it once. I paid it forty times last week and I'm the coach.",
    icon: '/achievements/bout-learning-tax.webp',
  },
  {
    id: 'bout-split-decision',
    category: 'bout',
    name: 'Split Decision',
    description: 'A draw. Nobody won. Nobody lost. The judges went home confused and so did I.',
    icon: '/achievements/bout-split-decision.webp',
  },
  {
    id: 'bout-ko-artist',
    category: 'bout',
    name: 'KO Artist',
    description: 'Checkmate is just a knockout where the referee is math.',
    icon: '/achievements/bout-ko-artist.webp',
    thresholds: [1, 5, 25, 100, 500],
  },
  {
    id: 'bout-went-the-distance',
    category: 'bout',
    name: 'Went the Distance',
    description: 'Every round. Every bell. Somewhere a training montage is playing about you.',
    icon: '/achievements/bout-went-the-distance.webp',
  },
  {
    id: 'bout-judges-favorite',
    category: 'bout',
    name: "Judges' Favorite",
    description: "You didn't knock me out, you just quietly took all my pawns. Colder, honestly.",
    icon: '/achievements/bout-judges-favorite.webp',
    thresholds: [1, 5, 25, 100],
  },
  {
    id: 'bout-hometown-decision',
    category: 'bout',
    name: 'Hometown Decision',
    description: 'Dead even and they gave it to you. The crowd loves you. I demand an inquiry.',
    icon: '/achievements/bout-hometown-decision.webp',
  },
  {
    id: 'bout-meltdown-button',
    category: 'bout',
    name: 'The Meltdown Button',
    description: 'I was WINNING. I want that recorded: I was winning, and this still happened.',
    icon: '/achievements/bout-meltdown-button.webp',
  },
  {
    id: 'bout-buzzer-beater',
    category: 'bout',
    name: 'Buzzer Beater',
    description: 'Under ten seconds left and you found mate. I need to sit down. I need to sit down more.',
    icon: '/achievements/bout-buzzer-beater.webp',
  },
  {
    id: 'bout-time-to-spare',
    category: 'bout',
    name: 'Time to Spare',
    description: 'You won with two minutes still on the clock. You could have used it. You chose not to. Rude.',
    icon: '/achievements/bout-time-to-spare.webp',
  },
  {
    id: 'bout-ring-fists',
    category: 'bout',
    name: 'Ring Fists',
    description: 'Punches landed in the ring, between chess moves. Your hands and your brain are finally on the same payroll.',
    icon: '/achievements/bout-ring-fists.webp',
    thresholds: [10, 50, 200, 1000, 5000],
  },
  {
    id: 'bout-clean-card',
    category: 'bout',
    name: 'Clean Card',
    description: 'A judge scored you ninety or better for a round. That judge and I are no longer speaking.',
    icon: '/achievements/bout-clean-card.webp',
    band: 'contender',
  },
  {
    id: 'bout-and-still',
    category: 'bout',
    name: 'And STILL Champion',
    description: "Five Fight Nights, five wins. Defend the belt or I'm taking it back.",
    icon: '/achievements/bout-and-still.webp',
  },
  {
    id: 'bout-championship-rounds',
    category: 'bout',
    name: 'Championship Rounds',
    description: 'Thirty-three minutes of chess boxing. Your cardio is now a chess piece.',
    icon: '/achievements/bout-championship-rounds.webp',
  },
  {
    id: 'bout-up-the-ladder',
    category: 'bout',
    name: 'Up the Ladder',
    description: 'I stopped going easy on you several levels ago. This is concerning.',
    icon: '/achievements/bout-up-the-ladder.webp',
    levelTiered: true,
  },
  {
    id: 'bout-sparring-partner',
    category: 'bout',
    name: 'Sparring Partner',
    description: 'Exhibition bouts. No stakes, all heart. You fight me when nobody is even counting, and I notice.',
    icon: '/achievements/bout-sparring-partner.webp',
    thresholds: [1, 10, 50, 200],
  },

  // ── Finishing moves (all detected by replaying the bout's real moves) ─────
  {
    id: 'mate-her-majesty',
    category: 'checkmate',
    name: 'Her Majesty',
    description: 'A queen mate. She files the paperwork AND performs the execution. Terrifying.',
    icon: '/achievements/mate-her-majesty.webp',
  },
  {
    id: 'mate-the-lawnmower',
    category: 'checkmate',
    name: 'The Lawnmower',
    description: "A rook mate. One straight line, no mercy. I heard it coming and still couldn't move.",
    icon: '/achievements/mate-the-lawnmower.webp',
  },
  {
    id: 'mate-long-distance-call',
    category: 'checkmate',
    name: 'Long-Distance Call',
    description: 'Mated by a bishop from across the board. I never even saw the area code.',
    icon: '/achievements/mate-long-distance-call.webp',
  },
  {
    id: 'mate-the-horse-kick',
    category: 'checkmate',
    name: 'The Horse Kick',
    description: 'A knight mate. The only piece that jumps, and it landed on my king.',
    icon: '/achievements/mate-the-horse-kick.webp',
  },
  {
    id: 'mate-pawnbroker',
    category: 'checkmate',
    name: 'Pawnbroker',
    description: 'Mated by a PAWN. The smallest guy on the board just retired my king. I need a minute.',
    icon: '/achievements/mate-pawnbroker.webp',
    band: 'contender',
  },
  {
    id: 'mate-the-quiet-step',
    category: 'checkmate',
    name: 'The Quiet Step',
    description: "You moved your KING and I got checkmated. I looked it up. It's legal.",
    icon: '/achievements/mate-the-quiet-step.webp',
    band: 'champion',
  },
  {
    id: 'mate-castle-doctrine',
    category: 'checkmate',
    name: 'Castle Doctrine',
    description: 'Checkmate BY CASTLING. Do you know the odds? I do. I calculated them mid-collapse.',
    icon: '/achievements/mate-castle-doctrine.webp',
    band: 'undisputed',
  },
  {
    id: 'mate-the-sneak',
    category: 'checkmate',
    name: 'The Sneak',
    description: 'En passant checkmate. The rarest crime in chess, committed in front of everyone.',
    icon: '/achievements/mate-the-sneak.webp',
    band: 'undisputed',
  },
  {
    id: 'mate-coronation-day',
    category: 'checkmate',
    name: 'Coronation Day',
    description: 'A pawn walked the whole board, got crowned, and delivered mate in the same breath. Cinema.',
    icon: '/achievements/mate-coronation-day.webp',
    band: 'champion',
  },
  {
    id: 'mate-philidors-ghost',
    category: 'checkmate',
    name: "Philidor's Ghost",
    description: 'A smothered mate. My own pieces boxed me in. This is a betrayal on several levels.',
    icon: '/achievements/mate-philidors-ghost.webp',
    band: 'champion',
  },
  {
    id: 'mate-back-rank-business',
    category: 'checkmate',
    name: 'Back Rank Business',
    description: 'Back rank. I KNOW about the back rank. Everyone knows about the back rank. And yet.',
    icon: '/achievements/mate-back-rank-business.webp',
  },
  {
    id: 'chess-speedrun',
    category: 'checkmate',
    name: 'Speedrun',
    description: "Checkmate in under ten moves. I've had warmups longer than that game.",
    icon: '/achievements/chess-speedrun.webp',
    band: 'contender',
  },
  {
    id: 'chess-the-marathon',
    category: 'checkmate',
    name: 'The Marathon',
    description: 'Sixty moves of chess boxing. We aged together in that ring.',
    icon: '/achievements/chess-the-marathon.webp',
  },
  {
    id: 'chess-never-needed-her',
    category: 'checkmate',
    name: 'Never Needed Her',
    description: "You lost your queen and won by knockout anyway. That's not a comeback, that's a statement.",
    icon: '/achievements/chess-never-needed-her.webp',
    band: 'contender',
  },
  {
    id: 'chess-untouchable',
    category: 'checkmate',
    name: 'Untouchable',
    description: 'A knockout without losing a single piece. Not one. I checked the tape frame by frame.',
    icon: '/achievements/chess-untouchable.webp',
    band: 'champion',
  },
  {
    id: 'chess-total-demolition',
    category: 'checkmate',
    name: 'Total Demolition',
    description: "Everything I owned was gone by the end. The king doesn't count. He never counts.",
    icon: '/achievements/chess-total-demolition.webp',
    band: 'contender',
  },
  {
    id: 'chess-field-promotion',
    category: 'checkmate',
    name: 'Field Promotion',
    description: "A pawn made it all the way across. I watched every step and couldn't stop one of them.",
    icon: '/achievements/chess-field-promotion.webp',
  },
  {
    id: 'chess-the-long-con',
    category: 'checkmate',
    name: 'The Long Con',
    description: 'You promoted to a KNIGHT. On purpose. And it WORKED. I have questions and also respect.',
    icon: '/achievements/chess-the-long-con.webp',
    band: 'champion',
  },
  {
    id: 'chess-harassment-campaign',
    category: 'checkmate',
    name: 'Harassment Campaign',
    description: 'Ten checks in one bout. My king filed a complaint. It was denied.',
    icon: '/achievements/chess-harassment-campaign.webp',
  },

  // ── Openings (belt-tiered: tier = the Rookie level you beat with it on the
  //    board — win a bout featuring the opening, climb the belt by re-earning
  //    it at higher levels) ──────────────────────────────────────────────────
  {
    id: 'opening-caro-kann',
    category: 'opening',
    name: 'Caro-Kann',
    description: "The Caro-Kann was on the board and you didn't lose. Nobody survives the Caro-Kann that well. I've checked.",
    icon: '/achievements/opening-caro-kann.webp',
    levelTiered: true,
  },
  {
    id: 'opening-london',
    category: 'opening',
    name: 'London System',
    description: 'The London. Congratulations on your new personality.',
    icon: '/achievements/opening-london.webp',
    levelTiered: true,
  },
  {
    id: 'opening-sicilian',
    category: 'opening',
    name: 'Sicilian Defense',
    description: "A real Sicilian, on the board, on purpose. Most people just SAY they've played the Sicilian.",
    icon: '/achievements/opening-sicilian.webp',
    levelTiered: true,
  },
  {
    id: 'opening-kings-gambit',
    category: 'opening',
    name: "King's Gambit",
    description: 'A pawn, donated on move two, described as a plan. The worst part is that it worked.',
    icon: '/achievements/opening-kings-gambit.webp',
    levelTiered: true,
  },
  {
    id: 'opening-scandinavian',
    category: 'opening',
    name: 'Scandinavian Defense',
    description: 'Queen out by move two, like someone with nothing to lose. I respect it and I fear it.',
    icon: '/achievements/opening-scandinavian.webp',
    levelTiered: true,
  },
  {
    id: 'opening-french',
    category: 'opening',
    name: 'French Defense',
    description: 'The French. A bishop spent the whole game locked in a closet and somebody still won. That bishop believed.',
    icon: '/achievements/opening-french.webp',
    levelTiered: true,
  },
  {
    id: 'opening-ruy-lopez',
    category: 'opening',
    name: 'Ruy Lopez',
    description: "The Ruy Lopez. They call it the Spanish Torture. Someone at this board got tortured, and it wasn't you.",
    icon: '/achievements/opening-ruy-lopez.webp',
    levelTiered: true,
  },
  {
    id: 'opening-italian',
    category: 'opening',
    name: 'Italian Game',
    description: 'The Italian Game. Four hundred years of theory, used to bully me specifically.',
    icon: '/achievements/opening-italian.webp',
    levelTiered: true,
  },
  {
    id: 'opening-queens-gambit',
    category: 'opening',
    name: "Queen's Gambit",
    description: "The Queen's Gambit. A pawn was offered. Regret followed. That's the whole opening, and it's undefeated.",
    icon: '/achievements/opening-queens-gambit.webp',
    levelTiered: true,
  },
  {
    id: 'opening-kings-indian',
    category: 'opening',
    name: "King's Indian",
    description: "The King's Indian. The whole center, handed over, then taken back with interest. A beautiful scam.",
    icon: '/achievements/opening-kings-indian.webp',
    levelTiered: true,
  },
  {
    id: 'opening-petroff',
    category: 'opening',
    name: 'Petroff Defense',
    description: "The Petroff. The chess equivalent of saying 'no, you.' Somehow a real opening. Somehow it worked.",
    icon: '/achievements/opening-petroff.webp',
    levelTiered: true,
  },
  {
    id: 'opening-scotch',
    category: 'opening',
    name: 'Scotch Game',
    description: 'The Scotch Game. The center exploded on move three and only one of us had a plan.',
    icon: '/achievements/opening-scotch.webp',
    levelTiered: true,
  },
  {
    id: 'opening-slav',
    category: 'opening',
    name: 'Slav Defense',
    description: 'The Slav. A brick wall with a zip code. I ran into it at full speed.',
    icon: '/achievements/opening-slav.webp',
    levelTiered: true,
  },
  {
    id: 'opening-grunfeld',
    category: 'opening',
    name: 'Grünfeld Defense',
    description: 'The Grünfeld. I was GIVEN the center. It was a trap. The center was a trap.',
    icon: '/achievements/opening-grunfeld.webp',
    levelTiered: true,
  },
  {
    id: 'opening-nimzo-indian',
    category: 'opening',
    name: 'Nimzo-Indian',
    description: 'The Nimzo-Indian. My pawns got doubled and so did my regrets.',
    icon: '/achievements/opening-nimzo-indian.webp',
    levelTiered: true,
  },
  {
    id: 'opening-english',
    category: 'opening',
    name: 'English Opening',
    description: 'The English Opening. It starts sideways and ends badly. For me, specifically.',
    icon: '/achievements/opening-english.webp',
    levelTiered: true,
  },
  {
    id: 'opening-pirc',
    category: 'opening',
    name: 'Pirc Defense',
    description: 'The Pirc. Quiet, patient, and then suddenly everywhere. Frankly, rude.',
    icon: '/achievements/opening-pirc.webp',
    levelTiered: true,
  },
  {
    id: 'opening-witty-alien',
    category: 'opening',
    name: 'Witty Alien',
    description: "MY opening. Beaten with MY opening. This is either flattery or treason and I haven't decided.",
    icon: '/achievements/opening-witty-alien.webp',
    levelTiered: true,
  },

  // ── Puzzles ───────────────────────────────────────────────────────────────
  {
    id: 'puzzle-first-solve',
    category: 'puzzle',
    name: 'First Solve',
    description: "Your first correct puzzle. I saw the whole thing. I'm going to be talking about it for a while.",
    icon: '/achievements/puzzle-first-solve.webp',
  },
  {
    id: 'puzzle-first-miss',
    category: 'puzzle',
    name: 'Swing and a Miss',
    description: 'Your first wrong answer. Congratulations, you are officially a chess player. That is the entry fee.',
    icon: '/achievements/puzzle-swing-and-a-miss.webp',
  },
  {
    id: 'puzzle-grinder',
    category: 'puzzle',
    name: 'Puzzle Grinder',
    description: 'Puzzles solved, and counting. Your pattern recognition is now legally a superpower.',
    icon: '/achievements/puzzle-grinder.webp',
    thresholds: [10, 50, 200, 1000, 5000],
  },
  {
    id: 'puzzle-combo-meal',
    category: 'puzzle',
    name: 'Combo Meal',
    description: 'A streak of correct answers, no misses. The multiplier has never been more proud of anyone.',
    icon: '/achievements/puzzle-combo-meal.webp',
    thresholds: [3, 5, 8, 12], // best combo in a session (high-water)
  },
  {
    id: 'puzzle-twenty-in-a-session',
    category: 'puzzle',
    name: 'Twenty Deep',
    description: 'Twenty puzzles solved in one session. Twenty. I have told no one. I have told everyone.',
    icon: '/achievements/puzzle-twenty-in-a-session.webp',
    band: 'contender',
  },
  {
    id: 'puzzle-whiffs',
    category: 'puzzle',
    name: 'The Whiff Collection',
    description: 'Wrong answers, lifetime. Every one of them taught you something, and every one of them made my day.',
    icon: '/achievements/puzzle-whiffs.webp',
    thresholds: [10, 50, 200, 1000],
  },
  {
    id: 'puzzle-bounce-back',
    category: 'puzzle',
    name: 'Bounce Back',
    description: 'Struck out in the first segment, then solved five anyway. That is the whole sport in one session.',
    icon: '/achievements/puzzle-bounce-back.webp',
    band: 'contender',
  },
  {
    id: 'puzzle-flawless',
    category: 'puzzle',
    name: 'Flawless',
    description: "A full flawless session. I checked the math twice because frankly I didn't believe the math.",
    icon: '/achievements/puzzle-flawless.webp',
    thresholds: [1, 2, 3, 4], // tier = longest flawless duration band (8/16/24/32 min)
  },

  // ── Training ──────────────────────────────────────────────────────────────
  {
    id: 'training-first-workout',
    category: 'training',
    name: 'Day One',
    description: 'Your first workout is in the books. I am the book. I am also the pen.',
    icon: '/achievements/training-day-one.webp',
  },
  {
    id: 'training-first-punch',
    category: 'training',
    name: 'First Punch',
    description: 'One punch, counted. The bag did not see it coming. The bag never sees anything coming.',
    icon: '/achievements/training-first-punch.webp',
  },
  {
    id: 'training-twenty-five',
    category: 'training',
    name: 'Twenty-Five',
    description: 'Twenty-five punches. I have told no one. I have told everyone.',
    icon: '/achievements/training-twenty-five.webp',
  },
  {
    id: 'training-hundred-club',
    category: 'training',
    name: 'Hundred Club',
    description: 'A hundred punches in one session. Your hands should file for overtime.',
    icon: '/achievements/training-hundred-club.webp',
    band: 'contender',
  },
  {
    id: 'training-thousand-fists',
    category: 'training',
    name: 'Thousand Fists',
    description: "Punches, lifetime. At some point this stopped being a chess app and I didn't stop you.",
    icon: '/achievements/training-thousand-fists.webp',
    thresholds: [50, 200, 1000, 5000, 25000],
  },
  {
    id: 'training-punch-clock',
    category: 'training',
    name: 'Punch Clock',
    description: 'Workouts finished. You keep showing up, and I keep the count, and neither of us is stopping.',
    icon: '/achievements/training-punch-clock.webp',
    thresholds: [3, 10, 50, 200, 1000],
  },
  {
    id: 'training-clock-in',
    category: 'training',
    name: 'Gym Minutes',
    description: 'Minutes in the gym with me. Every one of them is written down somewhere you will never find.',
    icon: '/achievements/training-clock-in.webp',
    thresholds: [15, 60, 300, 1000, 5000],
  },
  {
    id: 'training-fired-up',
    category: 'training',
    name: 'Fired Up',
    description: 'Eighty punches in one round. Your next chess round is legally required to be better. House rules.',
    icon: '/achievements/training-fired-up.webp',
  },
  {
    id: 'training-first-round',
    category: 'training',
    name: 'On the Board',
    description: 'Points in a round. Real ones. The scoreboard is now aware of you and it is nervous.',
    icon: '/achievements/training-first-round.webp',
  },
  {
    id: 'training-new-belt-day',
    category: 'training',
    name: 'New Belt Day',
    description: 'A personal best. Your old best is in the locker room questioning its life choices.',
    icon: '/achievements/training-new-belt-day.webp',
    thresholds: [1, 5, 25, 100],
  },
  {
    id: 'training-round-of-your-life',
    category: 'training',
    name: 'Round of Your Life',
    description: 'Your best single round, ever. I would review the tape but it would just embarrass the tape.',
    icon: '/achievements/training-round-of-your-life.webp',
    thresholds: [100, 250, 500, 1000], // best-round points (high-water)
  },
  {
    id: 'training-full-shift',
    category: 'training',
    name: 'Full Shift',
    description: 'A thirty-two minute session, start to finish. Go drink water. I mean it. Water.',
    icon: '/achievements/training-full-shift.webp',
    band: 'contender',
  },
  {
    id: 'training-double-shift',
    category: 'training',
    name: 'Double Shift',
    description: 'Two full sessions in one day. The gym has a cot in the back if it comes to that.',
    icon: '/achievements/training-double-shift.webp',
  },

  // ── Dedication ────────────────────────────────────────────────────────────
  {
    id: 'dedication-first-day',
    category: 'dedication',
    name: 'Showed Up',
    description: 'Your first day. Everything after this is a streak. No pressure. Some pressure.',
    icon: '/achievements/dedication-first-day.webp',
  },
  {
    id: 'dedication-the-regular',
    category: 'dedication',
    name: 'The Regular',
    description: 'Days in a row. I see you more than I see my own king, and he lives here.',
    icon: '/achievements/dedication-the-regular.webp',
    thresholds: [2, 7, 30, 100, 365],
  },
  {
    id: 'dedication-both-barrels',
    category: 'dedication',
    name: 'Both Barrels',
    description: 'A workout AND a bout on the same day. You did the whole sport in one day. On purpose.',
    icon: '/achievements/dedication-both-barrels.webp',
    band: 'contender',
  },
  {
    id: 'dedication-early-bird',
    category: 'dedication',
    name: 'Early Bird',
    description: 'Chess boxing before eight in the morning. The sun was barely up and you were already hitting things.',
    icon: '/achievements/dedication-early-bird.webp',
  },
  {
    id: 'dedication-lunch-break',
    category: 'dedication',
    name: 'Lunch Break',
    description: 'A session at lunch. Everyone else ate a sandwich. You ate a bishop.',
    icon: '/achievements/dedication-lunch-break.webp',
  },
  {
    id: 'dedication-weekend-warrior',
    category: 'dedication',
    name: 'Weekend Warrior',
    description: 'A weekend session. You could have been anywhere. You chose me and a punching bag.',
    icon: '/achievements/dedication-weekend-warrior.webp',
  },
  {
    id: 'dedication-comeback-kid',
    category: 'dedication',
    name: 'Comeback Kid',
    description: 'You came back. I kept the campfire going. I never doubted you. I doubted you a medium amount.',
    icon: '/achievements/dedication-comeback-kid.webp',
  },
  {
    id: 'dedication-night-shift',
    category: 'dedication',
    name: 'Night Shift',
    description: "It's the middle of the night and you chose chess boxing. Correct choice. Go to bed.",
    icon: '/achievements/dedication-night-shift.webp',
  },

  // ── Shame (secret until earned — the Dungeon Crawler Carl specialty) ──────
  {
    id: 'shame-glass-jaw',
    category: 'shame',
    name: 'Glass Jaw',
    description: "Knocked out before the gloves even came on. I had a puncher's chance. Sorry. Not that sorry.",
    icon: '/achievements/shame-glass-jaw.webp',
    secret: true,
  },
  {
    id: 'shame-flagged',
    category: 'shame',
    name: 'Flagged',
    description: 'You had all that time. You spent it like a lottery winner. The clock says hi.',
    icon: '/achievements/shame-flagged.webp',
    secret: true,
  },
  {
    // RETIRED (the 3-wrong round-ending rule was removed). No longer grantable;
    // the entry stays so existing holders still see it on their profile.
    id: 'shame-three-strikes',
    category: 'shame',
    name: 'Three Strikes',
    description: "Struck out in the opening segment. The puzzles started a group chat about you. I'm in it.",
    icon: '/achievements/shame-three-strikes.webp',
    secret: true,
  },
  {
    id: 'shame-full-carlsberg',
    category: 'shame',
    name: 'The Full Carlsberg',
    description: "Five losses in one day and you kept getting back up. That's the most boxer thing I've ever seen. Now go drink water.",
    icon: '/achievements/shame-full-carlsberg.webp',
    secret: true,
  },
];

const BY_ID = new Map(ACHIEVEMENT_CATALOG.map((d) => [d.id, d]));

export function getAchievementDef(id: string): AchievementDef | undefined {
  return BY_ID.get(id);
}
