/**
 * Progressive TTS cache for Rookie's voice.
 *
 * The idea: generate audio once, serve it forever. The library grows
 * over time so costs approach zero.
 *
 * Layer 1: Hardcoded quips — pre-generated by scripts/generate-rookie-audio.ts
 * Layer 2: Personalized quips — generated on first use, cached permanently
 *
 * Cache key = MD5 hash of the exact text. Same text = same file, always.
 *
 * Flow:
 *   1. Text comes in (hardcoded or generated)
 *   2. Check manifest for MD5(text) → filename
 *   3. HIT:  return /rookie-voice/{filename} (no API call)
 *   4. MISS: call ElevenLabs, save MP3, update manifest, return audio
 */

import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';

const VOICE_DIR = path.join(process.cwd(), 'public', 'rookie-voice');
const MANIFEST_PATH = path.join(VOICE_DIR, 'manifest.json');

// In-memory manifest — loaded once, updated on writes
let manifest: Record<string, string> | null = null;

function getManifest(): Record<string, string> {
  if (manifest) return manifest;
  try {
    manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf-8'));
  } catch {
    manifest = {};
  }
  return manifest!;
}

function saveManifest(): void {
  fs.mkdirSync(VOICE_DIR, { recursive: true });
  fs.writeFileSync(MANIFEST_PATH, JSON.stringify(getManifest(), null, 2));
}

function textToHash(text: string): string {
  return crypto.createHash('md5').update(text).digest('hex');
}

export interface CacheLookupResult {
  /** Whether the audio was found in cache */
  hit: boolean;
  /** Public URL path to the audio file (if cached) */
  url: string | null;
  /** Base64 audio data (if cached and readFile was requested) */
  audioBase64: string | null;
}

/**
 * Check if audio for this text already exists in the cache.
 */
export function lookupVoiceCache(text: string, readFile = false): CacheLookupResult {
  const m = getManifest();
  const filename = m[text];

  if (!filename) {
    return { hit: false, url: null, audioBase64: null };
  }

  const filepath = path.join(VOICE_DIR, filename);
  if (!fs.existsSync(filepath)) {
    // Manifest entry exists but file is missing — stale entry
    return { hit: false, url: null, audioBase64: null };
  }

  let audioBase64: string | null = null;
  if (readFile) {
    audioBase64 = fs.readFileSync(filepath).toString('base64');
  }

  return {
    hit: true,
    url: `/rookie-voice/${filename}`,
    audioBase64,
  };
}

/**
 * Save a generated audio recording to the cache.
 * Returns the public URL path to the cached file.
 */
export function saveToVoiceCache(text: string, audioBuffer: Buffer): string {
  const hash = textToHash(text);
  const filename = `${hash}.mp3`;
  const filepath = path.join(VOICE_DIR, filename);

  fs.mkdirSync(VOICE_DIR, { recursive: true });
  fs.writeFileSync(filepath, audioBuffer);

  const m = getManifest();
  m[text] = filename;
  saveManifest();

  return `/rookie-voice/${filename}`;
}

/**
 * Generate TTS via ElevenLabs and cache the result.
 * Returns base64-encoded audio.
 *
 * If the text is already cached, returns from cache (no API call).
 */
export async function generateAndCache(
  text: string,
  apiKey: string,
  voiceId: string
): Promise<{ audioBase64: string; fromCache: boolean }> {
  // Check cache first
  const cached = lookupVoiceCache(text, true);
  if (cached.hit && cached.audioBase64) {
    return { audioBase64: cached.audioBase64, fromCache: true };
  }

  // Generate via ElevenLabs
  const res = await fetch(
    `https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`,
    {
      method: 'POST',
      headers: {
        'xi-api-key': apiKey,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        text,
        model_id: 'eleven_turbo_v2_5',
        voice_settings: {
          stability: 0.35,
          similarity_boost: 0.55,
          style: 0.55,
        },
      }),
    }
  );

  if (!res.ok) {
    throw new Error(`ElevenLabs TTS error ${res.status}: ${await res.text()}`);
  }

  const arrayBuffer = await res.arrayBuffer();
  const audioBuffer = Buffer.from(arrayBuffer);

  // Cache it
  saveToVoiceCache(text, audioBuffer);

  return {
    audioBase64: audioBuffer.toString('base64'),
    fromCache: false,
  };
}

/**
 * Get cache stats for monitoring.
 */
export function getVoiceCacheStats(): {
  totalEntries: number;
  totalSizeBytes: number;
} {
  const m = getManifest();
  const entries = Object.keys(m).length;
  let totalSize = 0;

  for (const filename of Object.values(m)) {
    try {
      const stat = fs.statSync(path.join(VOICE_DIR, filename));
      totalSize += stat.size;
    } catch {
      // File missing — skip
    }
  }

  return { totalEntries: entries, totalSizeBytes: totalSize };
}
