/**
 * Extract react-chessboard's default piece SVGs into a data-URI map so the
 * OG share card can render the exact pieces the app's board uses.
 * Run: npx tsx scripts/extract-pieces.ts
 */
import * as fs from 'fs';
import * as path from 'path';
import { renderToStaticMarkup } from 'react-dom/server';
import { defaultPieces } from 'react-chessboard';
import sharp from 'sharp';

// Rasterize to PNG: satori blits PNGs fast but re-rasterizes SVG data URIs
// on every render (~1s each → 30s/card). PNG keeps renders well under 1s.
const PX = 160; // crisp at the ~76px board squares we draw

async function main() {
  const out: Record<string, string> = {};

  for (const [code, Comp] of Object.entries(defaultPieces)) {
    const svg = renderToStaticMarkup((Comp as (p: unknown) => JSX.Element)({}));
    const png = await sharp(Buffer.from(svg)).resize(PX, PX).png().toBuffer();
    out[code] = `data:image/png;base64,${png.toString('base64')}`;
  }

  const ts = `// AUTO-GENERATED by scripts/extract-pieces.ts — do not edit by hand.
// react-chessboard default pieces (the set the app board renders), rasterized to PNG data URIs.
export const PIECE_DATA_URIS: Record<string, string> = ${JSON.stringify(out, null, 2)};
`;

  const dest = path.join(process.cwd(), 'lib', 'og', 'chess-pieces.ts');
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, ts);
  console.log(`Wrote ${Object.keys(out).length} pieces to ${dest}`);
}

main();
